services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk11
    restart: unless-stopped
    ports:
      - "8088:8080"
    volumes:
      - "jenkins_home:/var/jenkins_home"

volumes:
  jenkins_home: